apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1-deployment
  labels:
    app: nginx1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx1
        image: nginx1:1.15.4
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx1-service
  labels:
   app: nginx1
spec:
  selector:
   app: nginx1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http