kind: Service
apiVersion: v1
metadata:
  name: service-skc-web
  labels:
   app: service-skc-web
spec:
  selector:
   app: skc-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http