apiVersion: v1
kind: Service
metadata:
  name: base-nginx-lb
  labels:
   app: base-nginx
spec:
  selector:
   app: base-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: LoadBalancer