apiVersion: v1
kind: Pod
metadata:
 name: skc-nginx
 labels:
  app: skc-web
spec:
 containers:
 - name: skc-nginx
   image: nginx
   ports:
   - containerPort: 80
   volumeMounts:
   - name: nginx-doc-root
     mountPath: /app/vol/html
   - name: nginx-persistent-root
     mountPath: /usr/docroot/html
   - name: secret-volume
     mountPath: /etc/secret-volume
   - name: config-volume
     mountPath: /etc/config
 volumes:
 - name: nginx-doc-root
   emptyDir: {}
 - name: nginx-persistent-root
   gcePersistentDisk: 
    pdName: shashank-disk1
    fsType: ext4
 - name: secret-volume
   secret:
    secretName: db-secret
 - name: config-volume
   configMap:
    name: fmap   
